[package]
name = "dypdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.0.0"
fixedbitset = "0.4.1"
approx = "0.5.1"
num-traits = "0.2"
rustc-hash = "1.1.0"